# Generated by Django 5.1.3 on 2024-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
