# Generated by Django 5.1.3 on 2024-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
